---
- name: Converge
  hosts: all
  become: true
  vars:
    domain_name: example.com
    subdomain_name: demo
    trojan_go_password: testing-password
    trojan_go_caddy_docker_users:
      - molecule
    trojan_go_caddy_deploy_stack: false
    trojan_go_caddy_system_packages:
      - curl
      - docker.io
      - python3-pip
      - uuid-runtime
  roles:
    - role: ../../roles/trojan_go_caddy
